CREATE TABLE goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    objective VARCHAR(255) NOT NULL,
    target_weight_kg DOUBLE PRECISION NOT NULL,
    pace VARCHAR(255) NOT NULL,
    diet_preset VARCHAR(255) NOT NULL,
    protein_pct INTEGER,
    carbs_pct INTEGER,
    fat_pct INTEGER,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_goals_user UNIQUE (user_id)
);
